import type { Category, MenuItem, Order, User } from "./types";

export const seedCategories: Category[] = [
  { id: "cat-1", nameAr: "المقبلات", nameEn: "Appetizers", sortOrder: 1 },
  { id: "cat-2", nameAr: "الأطباق الرئيسية", nameEn: "Main Courses", sortOrder: 2 },
  { id: "cat-3", nameAr: "المشويات", nameEn: "Grills", sortOrder: 3 },
  { id: "cat-4", nameAr: "المكالمات", nameEn: "Desserts", sortOrder: 4 },
  { id: "cat-5", nameAr: "المشروبات", nameEn: "Beverages", sortOrder: 5 },
];

export const seedMenuItems: MenuItem[] = [
  // Appetizers
  {
    id: "item-1",
    categoryId: "cat-1",
    nameAr: "حمص بالطحينة",
    nameEn: "Hummus with Tahini",
    descriptionAr: "حمص طازج مخفوق مع طحينة وزيت زيتون وليمون",
    descriptionEn: "Fresh chickpeas blended with tahini, olive oil, and lemon",
    price: 45,
    image: "https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-2",
    categoryId: "cat-1",
    nameAr: "فتوش",
    nameEn: "Fattoush Salad",
    descriptionAr: "سلطة فتوش مع خضار طازج وخبز مقرمش وصلصة رمان",
    descriptionEn: "Fresh vegetable salad with crispy bread and pomegranate dressing",
    price: 55,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-3",
    categoryId: "cat-1",
    nameAr: "ورق عنب",
    nameEn: "Stuffed Grape Leaves",
    descriptionAr: "ورق عنب محشي بالأرز والخضار مع الليمون",
    descriptionEn: "Grape leaves stuffed with rice and vegetables, served with lemon",
    price: 60,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-4",
    categoryId: "cat-1",
    nameAr: "تبولة",
    nameEn: "Tabbouleh",
    descriptionAr: "سلطة بقدونس طازج مع بطل وطماطم وعصير الليمون",
    descriptionEn: "Fresh parsley salad with bulgur, tomatoes, and lemon juice",
    price: 50,
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
    available: true,
  },
  // Main Courses
  {
    id: "item-5",
    categoryId: "cat-2",
    nameAr: "كبسة لحم",
    nameEn: "Lamb Kabsa",
    descriptionAr: "أرز بالتوابل مع لحم ضأن مطهو ببطء ومكسرات",
    descriptionEn: "Spiced rice with slow-cooked lamb and nuts",
    price: 180,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-6",
    categoryId: "cat-2",
    nameAr: "مقلوبة",
    nameEn: "Maqluba",
    descriptionAr: "أرز مقلوب مع باذنجان ولحم مطهو معصوب",
    descriptionEn: "Upside-down rice with eggplant and tender meat",
    price: 160,
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-7",
    categoryId: "cat-2",
    nameAr: "منسف",
    nameEn: "Mansaf",
    descriptionAr: "طبق أردني تقليدي مع لبن Jameed ولحم ضأن",
    descriptionEn: "Traditional Jordanian dish with Jameed yogurt and lamb",
    price: 200,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-8",
    categoryId: "cat-2",
    nameAr: "فتة حمص",
    nameEn: "Fatteh with Chickpeas",
    descriptionAr: "خبز مقرمش مع حمص وعلبة زبادي وصلصة البقدونس",
    descriptionEn: "Crispy bread with chickpeas, yogurt, and parsley sauce",
    price: 95,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop",
    available: true,
  },
  // Grills
  {
    id: "item-9",
    categoryId: "cat-3",
    nameAr: "شيش طاووق",
    nameEn: "Shish Tawook",
    descriptionAr: "دجاج متبل بالمتوابل مشوي على الفحم مع أرز وسلطة",
    descriptionEn: "Spiced chicken grilled over charcoal with rice and salad",
    price: 140,
    image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-10",
    categoryId: "cat-3",
    nameAr: "كفتة مشوية",
    nameEn: "Grilled Kofta",
    descriptionAr: "كرات لحم مشوية مع بصل وطماطم مشوية",
    descriptionEn: "Grilled meatballs with grilled onions and tomatoes",
    price: 130,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-11",
    categoryId: "cat-3",
    nameAr: "مشكل مشاوي",
    nameEn: "Mixed Grill Platter",
    descriptionAr: "تشكيلة من المشويات مع لحم ودجاج وكرات اللحم",
    descriptionEn: "Selection of grilled meats, chicken, and kofta",
    price: 250,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-12",
    categoryId: "cat-3",
    nameAr: "ripperز مشوية",
    nameEn: "Grilled Ribeyes",
    descriptionAr: "ستيك ريب آي مشوي مع صلصة الفطر والأعشاب",
    descriptionEn: "Grilled ribeye steak with mushroom herb sauce",
    price: 320,
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=300&fit=crop",
    available: false,
  },
  // Desserts
  {
    id: "item-13",
    categoryId: "cat-4",
    nameAr: "بقلاوة",
    nameEn: "Baklava",
    descriptionAr: "بقلاوة بالمكسرات مع شيرة القطر",
    descriptionEn: "Nut baklava with syrup",
    price: 65,
    image: "https://images.unsplash.com/photo-1519676867240-f03562e64571?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-14",
    categoryId: "cat-4",
    nameAr: "كنافة نابلسية",
    nameEn: "Nablusi Kunafa",
    descriptionAr: "كنافة بالجبنة مع شيرة القطر ومكسرات",
    descriptionEn: "Cheese kunafa with syrup and nuts",
    price: 80,
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-15",
    categoryId: "cat-4",
    nameAr: "أم علي",
    nameEn: "Om Ali",
    descriptionAr: "حلوى مصرية تقليدية بالحليب والمكسرات",
    descriptionEn: "Traditional Egyptian dessert with milk and nuts",
    price: 70,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-16",
    categoryId: "cat-4",
    nameAr: "آيس كريم بالفستق",
    nameEn: "Pistachio Ice Cream",
    descriptionAr: "آيس كريم بالفستق الحلبي مع صلصة الكراميل",
    descriptionEn: "Pistachio ice cream with caramel sauce",
    price: 55,
    image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=300&fit=crop",
    available: true,
  },
  // Beverages
  {
    id: "item-17",
    categoryId: "cat-5",
    nameAr: "شاي بالنعناع",
    nameEn: "Mint Tea",
    descriptionAr: "شاي أحمر طازج مع نعناع طازج",
    descriptionEn: "Fresh red tea with fresh mint",
    price: 20,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-18",
    categoryId: "cat-5",
    nameAr: "قهوة عربية",
    nameEn: "Arabic Coffee",
    descriptionAr: "قهوة عربية تقليدية بالهيل",
    descriptionEn: "Traditional Arabic coffee with cardamom",
    price: 25,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-19",
    categoryId: "cat-5",
    nameAr: "عصير رمان طازج",
    nameEn: "Fresh Pomegranate Juice",
    descriptionAr: "عصير رمان طازج معصور",
    descriptionEn: "Freshly squeezed pomegranate juice",
    price: 45,
    image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&h=300&fit=crop",
    available: true,
  },
  {
    id: "item-20",
    categoryId: "cat-5",
    nameAr: "لémon بالنعناع",
    nameEn: "Mint Lemonade",
    descriptionAr: "ليمون طازج مع نعناع وسكر",
    descriptionEn: "Fresh lemon with mint and sugar",
    price: 30,
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop",
    available: true,
  },
];

export const seedUsers: User[] = [
  { id: "user-1", email: "admin@tastytable.com", name: "Ahmed Admin", role: "admin", active: true },
  { id: "user-2", email: "kitchen@tastytable.com", name: "Sara Kitchen", role: "kitchen_staff", active: true },
];

export const seedOrders: Order[] = [
  {
    id: "order-1",
    orderNumber: "1001",
    customerName: "محمد علي",
    phone: "01012345678",
    orderType: "dine_in",
    tableNumber: 5,
    notes: "بدون بصل في الحمص",
    items: [
      { id: "oi-1", menuItemId: "item-1", nameAr: "حمص بالطحينة", nameEn: "Hummus with Tahini", quantity: 2, unitPrice: 45 },
      { id: "oi-2", menuItemId: "item-5", nameAr: "كبسة لحم", nameEn: "Lamb Kabsa", quantity: 1, unitPrice: 180 },
      { id: "oi-3", menuItemId: "item-17", nameAr: "شاي بالنعناع", nameEn: "Mint Tea", quantity: 3, unitPrice: 20 },
    ],
    status: "received",
    paymentStatus: "unpaid",
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: "order-2",
    orderNumber: "1002",
    customerName: "فاطمة أحمد",
    orderType: "takeaway",
    notes: "تيك أواي — 4 أشخاص",
    items: [
      { id: "oi-4", menuItemId: "item-9", nameAr: "شيش طاووق", nameEn: "Shish Tawook", quantity: 2, unitPrice: 140 },
      { id: "oi-5", menuItemId: "item-2", nameAr: "فتوش", nameEn: "Fattoush Salad", quantity: 1, unitPrice: 55 },
    ],
    status: "preparing",
    paymentStatus: "paid",
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: "order-3",
    orderNumber: "1003",
    customerName: "خالد حسن",
    orderType: "dine_in",
    tableNumber: 12,
    items: [
      { id: "oi-6", menuItemId: "item-11", nameAr: "مشكل مشاوي", nameEn: "Mixed Grill Platter", quantity: 1, unitPrice: 250 },
      { id: "oi-7", menuItemId: "item-13", nameAr: "بقلاوة", nameEn: "Baklava", quantity: 2, unitPrice: 65 },
      { id: "oi-8", menuItemId: "item-18", nameAr: "قهوة عربية", nameEn: "Arabic Coffee", quantity: 2, unitPrice: 25 },
    ],
    status: "ready",
    paymentStatus: "unpaid",
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
];
